// Generates src/ui/icons.ts by inlining Phosphor Icons SVG path data at build time.
// Keeps the runtime dependency-free: no icon font, no runtime SVG fetch, no DOM bloat.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const ASSETS = resolve("node_modules/@phosphor-icons/core/assets");

/** name -> [phosphor-slug, weight] */
const ICONS = {
  flagCheckered: ["flag-checkered", "fill"],
  flagPennant: ["flag-pennant", "fill"],
  lockKey: ["lock-key", "fill"],
  usersThree: ["users-three", "fill"],
  user: ["user", "fill"],
  gauge: ["gauge", "fill"],
  trophy: ["trophy", "fill"],
  crown: ["crown-simple", "fill"],
  timer: ["timer", "fill"],
  lightning: ["lightning", "fill"],
  copy: ["copy", "fill"],
  check: ["check", "bold"],
  checkCircle: ["check-circle", "fill"],
  caretRight: ["caret-right", "bold"],
  caretLeft: ["caret-left", "bold"],
  caretDown: ["caret-down", "bold"],
  arrowRight: ["arrow-right", "bold"],
  arrowClockwise: ["arrow-clockwise", "bold"],
  gearSix: ["gear-six", "fill"],
  play: ["play", "fill"],
  house: ["house", "fill"],
  signOut: ["sign-out", "bold"],
  warning: ["warning", "fill"],
  circleNotch: ["circle-notch", "bold"],
  keyboard: ["keyboard", "fill"],
  gameController: ["game-controller", "fill"],
  wifiHigh: ["wifi-high", "bold"],
  wifiSlash: ["wifi-slash", "bold"],
  cpu: ["cpu", "fill"],
  monitor: ["monitor", "fill"],
  x: ["x", "bold"],
  plus: ["plus", "bold"],
  minus: ["minus", "bold"],
  eye: ["eye", "fill"],
  shareNetwork: ["share-network", "fill"],
  confetti: ["confetti", "fill"],
  racingFlag: ["flag-banner-fold", "fill"],
  speedometer: ["speedometer", "fill"],
  sparkle: ["sparkle", "fill"],
  camera: ["video-camera", "fill"],
  skipForward: ["skip-forward", "fill"],
  hourglass: ["hourglass-high", "fill"],
  medal: ["medal", "fill"],
  arrowsClockwise: ["arrows-clockwise", "bold"],
  clock: ["clock", "fill"],
  paintBrush: ["paint-brush-broad", "fill"],
};

const inner = (svg) => svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").trim();

const entries = [];
const missing = [];
for (const [key, [slug, weight]] of Object.entries(ICONS)) {
  const suffix = weight === "regular" ? "" : `-${weight}`;
  const file = resolve(ASSETS, weight, `${slug}${suffix}.svg`);
  if (!existsSync(file)) {
    missing.push(`${slug} (${weight})`);
    continue;
  }
  entries.push(`  ${key}: ${JSON.stringify(inner(readFileSync(file, "utf8")))},`);
}

if (missing.length) {
  console.error("Missing Phosphor icons:\n  " + missing.join("\n  "));
  process.exit(1);
}

writeFileSync(
  resolve("src/ui/icons.ts"),
  `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit.
// Source: @phosphor-icons/core (MIT). Path data inlined so the bundle ships zero icon runtime.

const PATHS = {
${entries.join("\n")}
} as const;

export type IconName = keyof typeof PATHS;

/** Returns an inline <svg> string. \`size\` is any CSS length; defaults to 1em. */
export function icon(name: IconName, cls = ""): string {
  return \`<svg class="ph \${cls}" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true" focusable="false">\${PATHS[name]}</svg>\`;
}

export function iconEl(name: IconName, cls = ""): SVGElement {
  const tpl = document.createElement("template");
  tpl.innerHTML = icon(name, cls);
  return tpl.content.firstElementChild as SVGElement;
}
`,
);

console.log(`Generated src/ui/icons.ts with ${entries.length} Phosphor icons.`);
